/* FETCH  COUNTRIES BEGIN */
export const FETCH_COUNTRIES_BEGIN = "FETCH_COUNTRIES_BEGIN";
/* FETCH  COUNTRIE SUCCESS */
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
/* FETCH  COUNTRIE FAILURE */
export const FETCH_COUNTRIES_FAILURE = "FETCH_COUNTRIES_FAILURE";

/* FETCH  COUNTRIE BY NAME BEGIN */
export const FETCH_COUNTRIES_BY_NAME_BEGIN = "FETCH_COUNTRIES_BY_NAME_BEGIN";

/* FETCH  COUNTRIE BY NAME SUCCESS */
export const FETCH_COUNTRIES_BY_NAME_SUCCESS =
  "FETCH_COUNTRIES_BY_NAME_SUCCESS";

/* FETCH  COUNTRIE BY NAME FAILURE */
export const FETCH_COUNTRIES_BY_NAME_FAILURE =
  "FETCH_COUNTRIES_BY_NAME_FAILURE";
