/* BEGIN */
export const FETCH_COUNTRIES_BEGIN = "FETCH_COUNTRIES_BEGIN";
/* SUCCESS */
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
/* FAILURE */
export const FETCH_COUNTRIES_FAILURE = "FETCH_COUNTRIES_FAILURE";
