/* FETCH  COUNTRIES BEGIN */
export const FETCH_COUNTRIES_BEGIN = "FETCH_COUNTRIES_BEGIN";
/* FETCH  COUNTRIE SUCCESS */
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
/* FETCH  COUNTRIE FAILURE */
export const FETCH_COUNTRIES_FAILURE = "FETCH_COUNTRIES_FAILURE";

/* FETCH  COUNTRIE BY NAME BEGIN */
export const FETCH_COUNTRIES_BY_NAME_BEGIN = "FETCH_COUNTRIES_BY_NAME_BEGIN";

/* FETCH  COUNTRIE BY NAME SUCCESS */
export const FETCH_COUNTRIES_BY_NAME_SUCCESS =
  "FETCH_COUNTRIES_BY_NAME_SUCCESS";

/* FETCH  COUNTRIE BY NAME FAILURE */
export const FETCH_COUNTRIES_BY_NAME_FAILURE =
  "FETCH_COUNTRIES_BY_NAME_FAILURE";

/* FETCH COUNTRIES BY REGION  BEGIN */
export const FETCH_COUNTRIES_BY_REGION_BEGIN =
  "FETCH_COUNTRIES_BY_REGION_BEGIN";

/* FETCH COUNTRIES BY REGION  SUCCESS */
export const FETCH_COUNTRIES_BY_REGION_SUCCESS =
  "FETCH_COUNTRIES_BY_REGION_SUCCESS";

/* FETCH COUNTRIES BY REGION  FAILURE */
export const FETCH_COUNTRIES_BY_REGION_FAILURE =
  "FETCH_COUNTRIES_BY_REGION_FAILURE";

/* FETCH COUNTRY BY NAME BEGIN */
export const FETCH_COUNTRY_BY_NAME_BEGIN = "FETCH_COUNTRY_BY_NAME_BEGIN";

/* FETCH COUNTRY BY NAME SUCCESS */
export const FETCH_COUNTRY_BY_NAME_SUCCESS = "FETCH_COUNTRY_BY_NAME_SUCCESS";

/* FETCH COUNTRY BY NAME FAILURE */
export const FETCH_COUNTRY_BY_NAME_FAILURE = "FETCH_COUNTRY_BY_NAME_FAILURE";
